- become: yes
  hosts: all
  name: vm_config

  # install prometheus node exporter
  roles:
  - cloudalchemy.node_exporter

  tasks:
    - name: Add the student user
      user:
        name: "{{ ansible_hostname }}"
        
    - name: Add SSH key to student user
      authorized_key:
        user: "{{ ansible_hostname }}"
        state: present
        key: "{{ lookup('file', 'keys/' + ansible_hostname + '.pub') }}"
      
