- become: yes
  hosts: all
  name: vm_config

  # install prometheus node exporter
  roles:
  - cloudalchemy.node_exporter

  tasks:
    - name: Add the student user
      user:
        name: "{{ ansible_hostname }}"
        groups: sudo
        
    - name: Add SSH key to student user
      authorized_key:
        user: "{{ ansible_hostname }}"
        state: present
        key: "{{ lookup('file', 'keys/' + ansible_hostname + '.pub') }}"
      
    - name: sudo without password for students
      copy:
        content: '%{{ ansible_hostname }} ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/97-student_nopasswd
        mode: 0440
    
    - name: install acl package
      package:
        name: acl
        state: present

    - name: Add user bob
      ansible.builtin.user:
        name: bob
        shell: /bin/bash

    - name: Add user linda
      ansible.builtin.user:
        name: linda
        shell: /bin/bash
      
