- become: yes
  hosts: all
  name: vm_config
  tasks:
    - name: Add the student user
      user:
        name: "{{ ansible_hostname }}"
        
    - name: Add SSH key to student user
      authorized_key:
        user: "{{ ansible_hostname }}"
        state: present
        key: "{{ lookup('file', 'keys/' + ansible_hostname + '.pub') }}"
      
    # - name: Install apache2
    #   apt:
    #     name: apache2
    #     update_cache: yes
    #     state: latest
      
    # - name: Enable mod_rewrite
    #   apache2_module:
    #     name: rewrite 
    #     state: present
    #   notify:
    #     - Restart apache2

  # handlers:
  #   - name: restart sshd
  #     service:
  #       name: sshd
  #       state: restarted
